<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Testing Arena</name>
   <tag></tag>
   <elementGuidId>82859b49-f87a-4d4d-aa1d-3673d39a0b65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='banner']/div/header/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7f26f83b-df06-4d86-8b56-b65b3fc579f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing Arena</value>
      <webElementGuid>6fc18bd9-39bd-4b91-8a57-61e9cb897da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banner&quot;)/div[@class=&quot;content&quot;]/header[1]/h1[1]</value>
      <webElementGuid>fb6effc9-fa03-449c-b77e-83bf951b87f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='banner']/div/header/h1</value>
      <webElementGuid>c8b9cd4a-7b82-4569-b914-283e249e1d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Testing'])[1]/following::h1[1]</value>
      <webElementGuid>80ca352e-7829-4d67-b0fd-ea2e6394b819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='webdriveruniversity.com'])[1]/preceding::h1[1]</value>
      <webElementGuid>551fb3e8-ee6d-474e-af33-69383056a160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Testing Arena']/parent::*</value>
      <webElementGuid>b81b045a-6ad5-434b-bded-4de3e2c107ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>2d7b0cbe-53ba-47fa-8807-1b33a4f9a337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Testing Arena' or . = 'Testing Arena')]</value>
      <webElementGuid>66368501-d250-4781-801d-f9c46a029c21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
